### ISSUE TITLE
Issues - tested on Debian 8

### ISSUE THREAD

**Issue by vasiler** [VirtuBox/nginx-ee#36] opened 2019-02-10 12:01 UTC
Hi,

At the interactive installation, I remain stuck when I have to respond if I want an automatic update.

"Do you want to setup nginx-ee auto-update cronjob ? (y/n)
Select an option [y/n]: y
Select an option [y/n]: y" 

When installing with parameters, I get errors. 

For "bash <(wget -O - virtubox.net/nginx-ee || curl -sL virtubox.net/nginx-ee) --dynamic --naxsi --cron" I have that in /tmp/nginx-ee.log:
Hunk #6 succeeded at 469 (offset 2 lines).
patching file src/http/v2/ngx_http_v2_encode.c
patching file src/http/v2/ngx_http_v2_filter_module.c          patching file src/http/v2/ngx_http_v2_table.c                  patching file src/event/ngx_event_openssl.c                    Hunk #1 succeeded at 355 with fuzz 1 (offset 25 lines).        
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by VirtuBox** [comment] 2019-02-16 16:27
Hello @vasiler,

have you tried to run the script since nginx-ee v3.5.1 was released ?
Because error in your logs seems to be related to the previous method used to download openssl. 

Please, can you try to run the script again and confirm if the issue is fixed ?

**Comment by vasiler** [comment] 2019-02-16 17:03
The previous version I tested successfully is 3.3.1

We just tested the script and it does not work. 
Command: bash <(wget -O - virtubox.net/nginx-ee || curl -sL virtubox.net/nginx-ee) --naxsi

Please see log: https://paie.ro/nginx-ee.zip

**Comment by VirtuBox** [comment] 2019-02-17 16:20
Hello @vasiler,

Issue seems to be related to openssl, not to debian 8. 
Can you try to compile nginx with nginx-ee develop branch ? 

Here the command to run : 

```bash
bash <(wget -O - virtubox.net/nginx-ee-dev || curl -sL virtubox.net/nginx-ee-dev) --naxsi
```

**Comment by vasiler** [comment] 2019-02-17 17:16
I tried, error again.

Error log https://paie.ro/nginx-ee2.zip

**Comment by VirtuBox** [comment] 2019-02-17 17:49
Thanks, I will run few tests on a VM to see if it's related to the gcc version available on debian 8 or something else.

**Comment by VirtuBox** [comment] 2019-02-18 02:37
Issue has been fixed with the last commit on develop branch.

```bash
Welcome to the nginx-ee bash script v3.5.2


##################################
 Compilation summary
##################################

 Detected OS : Debian GNU/Linux 8.11 (jessie)
 Detected Arch : x86_64

  - Nginx release : 1.15.8
  - Dynamic modules NO
  - Pagespeed : NO
  - Naxsi : YES
  - RTMP : NO

       Installing dependencies                [OK]
       Downloading additionals modules        [OK]
       Downloading zlib                       [OK]
       Downloading brotli                     [OK]
       Downloading openssl                    [OK]
       Downloading naxsi                      [OK]
       Downloading nginx                      [OK]
       Applying nginx patches                 [OK]
       Configuring nginx                      [OK]
       Compiling nginx                        [OK]
       Updating Nginx manual                  [OK]
       Performing final steps                 [OK]
       Checking nginx configuration           [OK]
       Nginx-ee was compiled successfully !

       Installation log : /tmp/nginx-ee.log
```

I will publish changes on master tomorrow.

**Comment by vasiler** [comment] 2019-02-18 15:51
Now is fine, but...

Tested on Chrome Mobile (Android) and does not work with ssl_ciphers from https://github.com/VirtuBox/nginx-ee/blob/master/etc/nginx/nginx.conf (ERR_SSL_VERSION_OR_CIPHER_MISMATCH)

**Comment by VirtuBox** [comment] 2019-02-18 22:29
Hello @vasiler, 
yes this ciphers suite is outdated. Proper TLS configuration is available in the [Wiki](https://github.com/VirtuBox/nginx-ee/wiki/Nginx-TLS-configuration)

**Closed** 2019-02-19 03:28 UTC
Labels: bug
