### ISSUE TITLE
NAXSI Installation not working

### ISSUE THREAD

**Issue by nsgoyat** [VirtuBox/nginx-ee#43] opened 2019-03-09 13:50 UTC
**Attach the following commands output**

- [ ] lsb_release -a : 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
- [ ] nginx -V : 
nginx version: nginx/1.14.0 (EasyEngine)

**Describe the bug**

I am using the following command to compile the nginx with NAXSI:
`bash <(wget -O - virtubox.net/nginx-ee || curl -sL virtubox.net/nginx-ee) --naxsi`

Kindly, check the image to see the output of /tmp/nginx-ee.log:

![Untitled](https://user-images.githubusercontent.com/36985369/54072400-4b7a0800-42a0-11e9-82bb-6b621e8b4cea.png)

**Comment by VirtuBox** [comment] 2019-03-09 15:41
Hello @nsgoyat,

I will take a look on this issue, it was working fine until yesterday.

Regards,

**Comment by nsgoyat** [comment] 2019-03-10 03:21
Today, I run the script again just to check if it's something wrong with my own setup. Usually, I use a slightly modified version of "wo-nginx'setup" script by you.

On a fresh VPS with Ubuntu 18.04, I ran the following commands only:

```
wget -qO wo wordops.se/tup && sudo bash wo
wo stack install
```

and then

`bash <(wget -O - virtubox.net/nginx-ee || curl -sL virtubox.net/nginx-ee) --naxsi`

Again, NAXSI installation failed and the outpur is following:

![Untitled2](https://user-images.githubusercontent.com/36985369/54080255-ac8df400-4311-11e9-946f-dc74af80e293.png)

**Comment by VirtuBox** [comment] 2019-03-11 18:03
Hello @nsgoyat, okay it seems to be related to naxsi release checkout. I will run few tests this evening

**Comment by nsgoyat** [comment] 2019-03-13 05:40
Tried it again today and it seems to be fixed now. NAXSI installation goes smoothly.

**Comment by nsgoyat** [comment] 2019-03-15 13:24
The issue is appearing again now...

**Comment by VirtuBox** [comment] 2019-03-15 16:00
Hello @nsgoyat,

I have noticed the issue too, I will run more tests to identify what is the cause of this error

**Comment by VirtuBox** [comment] 2019-03-21 19:40
Issue has been fixed with the PR https://github.com/VirtuBox/nginx-ee/pull/45

**Closed** 2019-03-22 02:45 UTC
Labels: bug
